### ISSUE TITLE
RediSearch HSET

### ISSUE THREAD

**Issue by b3z** [danitseitlin/redis-modules-sdk#39]
Since ft.add is depreciated they say you should use HSET because RedisSearch 2.0 is indexing on HSET. 
See https://oss.redislabs.com/redisearch/Commands/#ftadd

How do I have access to HSET using your module?

**Comment by b3z** [comment]
you might want to add some function in module which allows raw commands to ioredis?

**Comment by danitseitlin** [comment]
@b3z In order to access native Redis commands you could use the 'redis' data member. The redis data member exists in every redis module SDK class holds all the functionality of IORedis that is being used in this project.
The usage would look like:
```
const search = new Redisearch({host: '..', port: 123});
await search.redis.hset(...);
```

`you might want to add some function in module which allows raw commands to ioredis?`: The idea is good, Thank you for sharing. I will think it through and see how I can achieve that in the best way possible.

**Comment by b3z** [comment]
Oh sorry. I read your code but I missed that the redis attribute in Module is public. Then there might be no need for raw commands anymore. Thanks for the help.
